### ISSUE TITLE
Limitation Issue?

### ISSUE THREAD

**Issue by pcdependency** [choozn/react-parallax-mouse#25]
I have around 114 .png images that I am trying to use in a parallax banner but only around 10-20 of them are actually visible/rendering. All image elements show up in the DevTools Elements panel and show that they are translating, but 90% of them aren't rendering.

Are there any limitations to this package?

**Comment by choozn** [comment]
Hey @pcdependency,
the package itself does not have any limitations. The limitations in this case come from the browser and how they ensure performance. 114 different layers are definitely too many for a browser to handle. The fix for this is to group them. Images with the same factor values should be wrapped in one ``<MouseParallaxChild>`` element, instead of wrapping each one separately.

The problem in your case is most likely (as all elements seem to translate the way they should), that you are loading 114 images at the same time - Your browser might limit you on that one.
